# Generated by Django 5.0.4 on 2024-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/ordered')),
                ('tax', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
