# Generated by Django 5.0.4 on 2024-07-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_model',
            name='ph_loc',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
