# Generated by Django 5.0.4 on 2024-07-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_contact_model_ph_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ph_loc', models.CharField(max_length=3, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('postal', models.IntegerField()),
                ('cardno', models.IntegerField()),
                ('expiry', models.DateField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact_model',
        ),
        migrations.DeleteModel(
            name='credit_card',
        ),
        migrations.DeleteModel(
            name='delivery_model',
        ),
    ]
