# Generated by Django 5.0.4 on 2024-07-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_model_delete_contact_model_delete_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_model',
            name='expiry',
            field=models.CharField(max_length=10),
        ),
    ]
