# Generated by Django 5.0.4 on 2024-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_model_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='orderdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
