# Generated by Django 5.0.4 on 2024-07-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_model_orderdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_model',
            name='ph_loc',
        ),
    ]
