# Generated by Django 5.0.4 on 2024-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_model_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
