# Generated by Django 5.0.4 on 2024-07-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_model_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=225)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_model')),
            ],
        ),
    ]
