# Generated by Django 5.0.4 on 2024-07-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order_model'),
        ),
    ]
