# Generated by Django 5.0.4 on 2024-07-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_items_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_items',
            old_name='invoice',
            new_name='inv',
        ),
    ]
