# Generated by Django 5.0.4 on 2024-07-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_invoice_order_items_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/orders'),
        ),
    ]
