# Generated by Django 5.0.4 on 2024-07-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='card',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order_model',
            name='feetotal',
            field=models.IntegerField(null=True),
        ),
    ]
