# Generated by Django 5.0.4 on 2024-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_model_card_order_model_feetotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
